version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openresume-viewer-app
    ports:
      - "3000:3000" # Cambia el puerto si tu aplicación usa otro
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: production


